### ISSUE TITLE
Need to algorithms to the sample file

### ISSUE THREAD

**Issue by harshagr18** [sneaky-beaver/codechef-practice#4]
Please add a few algorithms from the web to the sample file to receive a valid pull request!

**Comment by sumitmohite0501** [comment]
please assign this to me under hacktoberfest label
and please tell which sample file

**Comment by harshagr18** [comment]
Feel free to add common snippets which are often used in CP to the sample.py file or improve efficiency of existing code or add a new solution of your own and submit a pull request.
